//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personalblog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Company { get; set; }
        public string Year { get; set; }
        public string Position { get; set; }
        public string Role { get; set; }
        public string Responsibilities { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public int Priority { get; set; }
        public string HighlightKey { get; set; }
        public int ProfileNo { get; set; }
    
        public virtual ProfileIdentity ProfileIdentity { get; set; }
    }
}
