//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personalblog
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileIdentity
    {
        public ProfileIdentity()
        {
            this.Contacts = new HashSet<Contact>();
            this.Educations = new HashSet<Education>();
            this.Experiences = new HashSet<Experience>();
            this.Profiles = new HashSet<Profile>();
            this.Skills = new HashSet<Skill>();
            this.SkillCategories = new HashSet<SkillCategory>();
        }
    
        public int ProfileNo { get; set; }
        public string Title { get; set; }
        public string ProfileSummary { get; set; }
        public string ResumeLocation { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Education> Educations { get; set; }
        public virtual ICollection<Experience> Experiences { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }
        public virtual ICollection<SkillCategory> SkillCategories { get; set; }
    }
}
