//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personalblog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FacebookId { get; set; }
        public string MailId { get; set; }
        public string Mobile { get; set; }
        public string Website { get; set; }
        public string Skype { get; set; }
        public string Location { get; set; }
        public string LinkedInId { get; set; }
        public string TwitterId { get; set; }
        public string GooglePlusId { get; set; }
        public int ProfileNo { get; set; }
    
        public virtual ProfileIdentity ProfileIdentity { get; set; }
    }
}
