//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personalblog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int SkillCategory { get; set; }
        public int Priority { get; set; }
        public int Proficiency { get; set; }
        public int ProfileNo { get; set; }
    
        public virtual ProfileIdentity ProfileIdentity { get; set; }
        public virtual SkillCategory SkillCategory1 { get; set; }
    }
}
